### ISSUE TITLE
Allow members without the "edit members" permission to edit their own information

### ISSUE THREAD

**Issue by benburwell** [benburwell/MCEMS-Site#37]
Allow members to edit both their own certifications and their own demographic info.

**Comment by jmankhan** [comment]
Is passport current being utilized? If not, we can use the idea mentioned below, if so, it should still work but it might be better to use passport.

Since you are getting the id of the member being observed already in /routes/member.js, I thought to simply compare it to the id of the current user. On line 287, we can add another if statement along the lines of 
if(id == req.session.member) { update = member;}
I'm not quite sure how to get the id of the current user though. Any tips?

**Comment by benburwell** [comment]
Passport is not being used. That was going to be for API authentication but never really came to fruition. Probably safe to get rid of it altogether.

But adding that clause to the if statement should take care of that permission issue for demographic data. Doing id==req.session.member._id should work.

I believe you'll also need to edit /views/members/edit.jade and probably the display_self function in /routes/member.js.

**Comment by benburwell** [comment]
FYI, Vagrantfile has been merged to master. [Download Vagrant](https://www.vagrantup.com) and you should be able to get the site up and running on your machine for development.
